version: "3.8"
services:
  api:
    build: .
    restart: on-failure
    ports:
      - "8085:8080"
    depends_on:
      - mysqldb
    environment:
      SPRING_APPLICATION_JSON: '{"spring.datasource.url" : "jdbc:mysql://mysqldb:3306/amazing"}'
    volumes:
      - db-data:/var/lib/mysql/
      - ./src/main/resources/db/migration:/flyway/sql
  mysqldb:
    platform: linux/x86_64
    image: mysql:8.0
    restart: on-failure
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: amazing
      MYSQL_USER: amazing
      MYSQL_PASSWORD: amazing
      MYSQL_ROOT_PASSWORD: root
volumes:
  db-data: